# FROM node:16.20.0 AS builder

# WORKDIR /src
# COPY pa_note_front /src

# RUN ls
# RUN npm install -g pnpm
# RUN pnpm install
# RUN pnpm build

FROM nginx:alpine-slim

RUN mkdir -p /usr/share/nginx/front/dist
 
COPY docker/front_nginx.conf /etc/nginx/nginx.conf

# COPY --from=builder /src/dist /usr/share/nginx/front/dist
COPY pa_note_front/dist /usr/share/nginx/front/dist

EXPOSE 3333