version: '3'
services:
  nginx:
    image: nginx:alpine-slim
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend

  frontend:
    image: panote_front:v1
    ports:
      - "3333:3333"

  backend:
    image: panote_server:v1
    ports:
      - "3004:3004"
    volumes:
      - ./panote_data:/etc/server/default